# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "email": "9745341@qqcom",
  "pass": "Mysql123456",
  "verifyCode": "string"
}

###

GET http://localhost:8080/api/user/currentUser
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI3Mjc0NDM1MzBAcXEuY29tIiwiYXV0aG9yaXR5IjpbInVzZXIiXSwiZXhwIjoxNTQ0MTk0NDUxfQ.7djP6THnQluD0Yq-l4nuXP7NpduADi2OawhhyTFM8DIij-CrJGqmBDTO4j_QvJLG
###

POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "username": "727443530@qq.com",
  "password": "Mysql123456"
}

###

GET http://localhost:8080/api/manager/user?pageSize=10&pageNum=0
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI3Mjc0NDM1MzBAcXEuY29tIiwiYXZhdGFyIjoiMjctMTU0NDAyNTIxMzcxNC5wbmciLCJhdXRob3JpdHkiOlsidXNlciJdLCJleHAiOjE1NDQ2MTAxMjN9.TLGugfqA_SPMpUHS1hcSHA8xsbQADG5ibhJL1AZr_HoVRbiZsQ_azbcTHl2AkAoF
###