package com.jc.crm.bean;

import java.util.Date;

public class Competitors {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competitors.competitor_id
     *
     * @mbg.generated
     */
    private Integer competitorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competitors.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competitors.ex_1
     *
     * @mbg.generated
     */
    private String ex1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competitors.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competitors.utime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competitors.types
     *
     * @mbg.generated
     */
    private String types;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competitors.isdeleted
     *
     * @mbg.generated
     */
    private Boolean isdeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competitors.holder
     *
     * @mbg.generated
     */
    private Integer holder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competitors.competitor_id
     *
     * @return the value of competitors.competitor_id
     *
     * @mbg.generated
     */
    public Integer getCompetitorId() {
        return competitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competitors.competitor_id
     *
     * @param competitorId the value for competitors.competitor_id
     *
     * @mbg.generated
     */
    public void setCompetitorId(Integer competitorId) {
        this.competitorId = competitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competitors.description
     *
     * @return the value of competitors.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competitors.description
     *
     * @param description the value for competitors.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competitors.ex_1
     *
     * @return the value of competitors.ex_1
     *
     * @mbg.generated
     */
    public String getEx1() {
        return ex1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competitors.ex_1
     *
     * @param ex1 the value for competitors.ex_1
     *
     * @mbg.generated
     */
    public void setEx1(String ex1) {
        this.ex1 = ex1 == null ? null : ex1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competitors.ctime
     *
     * @return the value of competitors.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competitors.ctime
     *
     * @param ctime the value for competitors.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competitors.utime
     *
     * @return the value of competitors.utime
     *
     * @mbg.generated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competitors.utime
     *
     * @param utime the value for competitors.utime
     *
     * @mbg.generated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competitors.types
     *
     * @return the value of competitors.types
     *
     * @mbg.generated
     */
    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competitors.types
     *
     * @param types the value for competitors.types
     *
     * @mbg.generated
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competitors.isdeleted
     *
     * @return the value of competitors.isdeleted
     *
     * @mbg.generated
     */
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competitors.isdeleted
     *
     * @param isdeleted the value for competitors.isdeleted
     *
     * @mbg.generated
     */
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competitors.holder
     *
     * @return the value of competitors.holder
     *
     * @mbg.generated
     */
    public Integer getHolder() {
        return holder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competitors.holder
     *
     * @param holder the value for competitors.holder
     *
     * @mbg.generated
     */
    public void setHolder(Integer holder) {
        this.holder = holder;
    }
}