package com.jc.crm.dao;

import com.jc.crm.bean.Competitors;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface CompetitorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competitors
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer competitorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competitors
     *
     * @mbg.generated
     */
    int insert(Competitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competitors
     *
     * @mbg.generated
     */
    int insertSelective(Competitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competitors
     *
     * @mbg.generated
     */
    Competitors selectByPrimaryKey(Integer competitorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competitors
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Competitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competitors
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Competitors record);
}