# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "email": "asuismn@163.com",
  "pass": "123456string",
  "verifyCode": "string"
}

###
POST http://localhost:8080/api/enterprise
Authorization: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhc3Vpc21uQDE2My5jb20iLCJleHAiOjE1NDI4ODQ3OTF9.0B6zVka9xW6cert254U3mcBbpCi1ihD5uv_dvd2UaciybX2YERRm3TvAQfp2Obv-
Content-Type: application/json

{}

###